### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by GeorgiosDrivas**
footer

I created a Footer.jsx component and placed it in the layout.jsx
This way, it is visible in every page.

A simple layout that includes the links you requested as well as a border top maching the color of the search bar border.
I have added some css in order to make it match the aesthetic of the website. The footer is not position:fixed as the header, so it will be placed at the end of the page every time.

Every link has it's title, and the github link has target _blank to redirect the user in another web page.
Feel free to message if you want any changes.

I have followed the guidlines, changing the branch name into a more precise one.

Issue: #32

### CODE REVIEW

**Comment by lambeboluwatife** [comment]
This is awesome.
Though the footer isn't that detailed but it will suffice for now since there's not that much content on the project.

And is the footer responsive?

**Comment by GeorgiosDrivas** [comment]
I haven't checked for responsiveness yet. Would you like me to check it before merging it?

**Comment by lambeboluwatife** [comment]
> I haven't checked for responsiveness yet. Would you like me to check it before merging it? 

Yes please 
So that aspect of the footer will be done.
Thank you

**Comment by GeorgiosDrivas** [comment]
I have checked the responsiveness of the footer. I made some adjustments, in the mobile view. Please review and inform me for any  changes you want.

**Review by lambeboluwatife — APPROVED** [review]
This is awesome and will suffice for now pending any changes in the project.
Thank you for your contribution.

**Pull request merged**
