### PR TITLE
feat-CHANGED  the CSS files into SASS/SCSS files #47

### PR DESCRIPTION
**Pull request by Daniel-C-Igbokwe**
I basically took all the pre-existing code from the index.css, global.css and responsive.css and repackaged them with some sass touch.
 You will find all  the sass files in the scss folder.
They are compiled to a single style.css file in a css folder.

### CODE REVIEW

**Comment by Saber1Y** [comment]
Why SASS? what if other contributors dont write SASS you should follow the language as it was created by the owner.

**Comment by Daniel-C-Igbokwe** [comment]
I suggested to implement sass in the project and lambeboluwatife gave me a go-ahead. 
And sass is still CSS. It just has some special features.

**Review by lambeboluwatife — CHANGES_REQUESTED** [review]
Your branch name isn't in the right format and it doesn't describe what you implemented but other things look good.

Please kindly make your branch name in line with the [CONTRIBUTING.md](https://github.com/lambeboluwatife/lbdflix/blob/main/CONTRIBUTING.md) guidelines.

**Comment by Daniel-C-Igbokwe** [comment]
No problem

**Comment by Daniel-C-Igbokwe** [comment]
Is the branch name in the right format now  lambeboluwatife?

**Pull request merged**
