### PR TITLE
Implemented SASS in the project

### PR DESCRIPTION
**Pull request by Daniel-C-Igbokwe**
I was able to change the vanilla css to scss, still retaining most of the styling. I will still like to improve on the sass in the future but for now this is what I've done.

### CODE REVIEW

**Comment by Daniel-C-Igbokwe** [comment]
I hope you like my work.

**Review by lambeboluwatife — CHANGES_REQUESTED** [review]
Looks great, but your PR didn't follow the contributing convention stated in the [Readme.md](https://github.com/lambeboluwatife/lbdflix/blob/main/README.md) and the [contribution.md](https://github.com/lambeboluwatife/lbdflix/blob/main/CONTRIBUTING.md).

Please kindly read through and follow the guidelines for the PR.
Thanks for your contribution.

and please use "Implemented SASS for the project" rather than "I implemented sass in the project for the first time".

**Comment by Daniel-C-Igbokwe** [comment]
Oh I'm sorry bro. I'll change it now

**Comment by lambeboluwatife** [comment]
> Oh I'm sorry bro. I'll change it now

Okay
Thank you

**Pull request closed without merging**
