### PR TITLE
Review Accordion

### PR DESCRIPTION
**Pull request by kmahesh18**
Reviews page got setup finely and Changed the layout of reviews too

### CODE REVIEW

**Comment by kmahesh18** [comment]
heyy @lambeboluwatife ..can you please check what secrets are revealed... I've solved the issue mentioned exactly and even enhanced the review system

**Comment by lambeboluwatife** [comment]
@kmahesh18 you did an amazing job. I really love it. As for the secrets, it just the API_KEYS that are being pushed to the codebase.
Don't worry about that, I'll fix it.

And again, you did great 😃

**Comment by kmahesh18** [comment]
> @kmahesh18 you did an amazing job. I really love it. As for the secrets, it just the API_KEYS that are being pushed to the codebase. Don't worry about that, I'll fix it.
> 
> And again, you did great 😃

ThankYou...I'm Just developing my skills participating in hacktober fest ... and i want to know when this pr gets merged so as i can complete and recieve badge in fest...

**Review by lambeboluwatife — APPROVED** [review]

**Comment by lambeboluwatife** [comment]
Yeah, it has been merged. I love that you used page.modules.css for the styling.
I'll say you are the first person I'll come across that use that.

**Pull request merged**
