### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by GeorgiosDrivas**
footer_pic

I created a Footer.jsx component and placed it in the layout.jsx 
This way, it is visible in every page.

A simple layout that includes the links you requested as well as a border top maching the color of the search bar border.
I have added some css in order to make it match the aesthetic of the website. The footer is not position:fixed as the header, so it will be placed at the end of the page every time.

Every link has it's title, and the github link has target _blank to redirect the user in another web page. 
Feel free to message if you want any changes.

Issue: #32

### CODE REVIEW

**Comment by lambeboluwatife** [comment]
Nice work. 
I've seen it but haven't fully reviewed it. I'll get back to you soon.
Thank you

**Review by lambeboluwatife — CHANGES_REQUESTED** [review]
Awesome job @GeorgiosDrivas but you didn't follow the contribution guidelines for your pull request.
Kindly check the contribution guidelines file on how to do that.
Thank you

**Comment by GeorgiosDrivas** [comment]
@lambeboluwatife I am really sorry, you are right. I will make sure to read the guidelines before making the necessary changes.

**Comment by lambeboluwatife** [comment]
> @lambeboluwatife I am really sorry, you are right. I will make sure to read the guidelines before making the necessary changes.

Thank you

**Pull request closed without merging**
